### ISSUE TITLE
Surge订阅提示Remote resource returned zero data

### ISSUE THREAD

**Issue by WYEEE** [Peng-YM/Sub-Store#44]
请问TF Surge下操作：

默认Default.conf配置下 - Surge安装模块Surge.sgmodule - 规则模式、打开了rewrite、MitM、脚本 - 到safari访问sub-store - 新建单个订阅 - 名称、机场链接、没有配置导入 - 完成 - 复制https://sub.store/download/TAG到Surge代理服务器新的策略组 -更新 -提示Remote resource returned zero data 返回数据为空

但是safari直接打开https://sub.store/download/TAG是有节点信息的，请问是哪一步出错了呢，感谢~~

入门小白，见谅。

**Comment by Peng-YM** [comment]
是不是Surge用了SSR节点

**Comment by WYEEE** [comment]
是的，机场只有SSR节点。

那请问大佬，SSR机场不能用sub.store吗？

**Comment by Peng-YM** [comment]
不是，Surge不支持SSR，所以substore过滤掉了所有的SSR节点

**Comment by dsh2595977663** [comment]
vmess节点可以使用吗？我vmess节点也显示不出来

**Comment by dsh2595977663** [comment]
作者你好，请问一下现在在sub-store里是不是没有关键词过滤的功能了？

**Comment by Peng-YM** [comment]
> vmess节点可以使用吗？我vmess节点也显示不出来

可以使用的，如果不能使用，请开一个新的issue报告问题

**Comment by Peng-YM** [comment]
> 作者你好，请问一下现在在sub-store里是不是没有关键词过滤的功能了？
> 
> 

有的，你用正则过滤器就可以实现相同的功能了

**Comment by dsh2595977663** [comment]
大佬，我把我节点链接发给你，你看看能不能通过sub-store导入进surge可以吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 中午1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)





  
vmess节点可以使用吗？我vmess节点也显示不出来
  
可以使用的，如果不能使用，请开一个新的issue报告问题

**Comment by Peng-YM** [comment]
> 大佬，我把我节点链接发给你，你看看能不能通过sub-store导入进surge可以吗？
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2022年5月21日(星期六) 中午1:31
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 
> vmess节点可以使用吗？我vmess节点也显示不出来
> 
>   
> 
> 可以使用的，如果不能使用，请开一个新的issue报告问题
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you commented.Message ID: ***@***.***&gt;

没问题

**Comment by dsh2595977663** [comment]
https://api.ikuuu.science/link/k6FJmFTRogtmnXEB?sub=3&amp;extend=1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)





  
大佬，我把我节点链接发给你，你看看能不能通过sub-store导入进surge可以吗？
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2022年5月21日(星期六) 中午1:31
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)
 
vmess节点可以使用吗？我vmess节点也显示不出来
 
可以使用的，如果不能使用，请开一个新的issue报告问题
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you commented.Message ID: @.***&gt;
  
没问题

**Comment by dsh2595977663** [comment]
可以导入，大佬我尝试过了，刚刚不知道为什么没有显示，现在好了，感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)





  
大佬，我把我节点链接发给你，你看看能不能通过sub-store导入进surge可以吗？
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2022年5月21日(星期六) 中午1:31
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)
 
vmess节点可以使用吗？我vmess节点也显示不出来
 
可以使用的，如果不能使用，请开一个新的issue报告问题
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you commented.Message ID: @.***&gt;
  
没问题

**Comment by dsh2595977663** [comment]
直接输入关键字"邀请"就好了...谢谢大佬,不打扰您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 中午1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)





  
作者你好，请问一下现在在sub-store里是不是没有关键词过滤的功能了？
  
有的，你用正则过滤器就可以实现相同的功能了

**Comment by dsh2595977663** [comment]
大佬我再问您一个问题,为什么我在substore里面成功保存github用户信息后依然无法上传配置呢?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)





  
大佬，我把我节点链接发给你，你看看能不能通过sub-store导入进surge可以吗？
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2022年5月21日(星期六) 中午1:31
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)
 
vmess节点可以使用吗？我vmess节点也显示不出来
 
可以使用的，如果不能使用，请开一个新的issue报告问题
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you commented.Message ID: @.***&gt;
  
没问题

**Comment by Peng-YM** [comment]
有没有正确使用token呢？请先按照教程配置好

**Comment by dsh2595977663** [comment]
大佬您好，策略组导入sub整理好的节点信息后能正常使用，但是在“外部资源”那里更新资源后策略组信息始终显示“Failed to parse remote resource data”，您知道是怎么回事吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)





 
有没有正确使用token呢？请先按照教程配置好

**Comment by Peng-YM** [comment]
github issue 用来沟通太低效了，你在其他平台找我吧

**Comment by dsh2595977663** [comment]
大佬您好，正则过滤我不太会，假如说我节点信息里面有“邀请”两个字，那么我应该"正则过滤-过滤模式-(?!)(邀请)"吗?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)





  
大佬，我把我节点链接发给你，你看看能不能通过sub-store导入进surge可以吗？
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "Peng-YM/Sub-Store"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2022年5月21日(星期六) 中午1:31
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [Peng-YM/Sub-Store] Surge订阅提示Remote resource returned zero data (#44)
 
vmess节点可以使用吗？我vmess节点也显示不出来
 
可以使用的，如果不能使用，请开一个新的issue报告问题
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you commented.Message ID: @.***&gt;
  
没问题

**Comment by Peng-YM** [comment]
模式选过滤，直接填“邀请”这两个字就可以
